In [1]:
import torch

In [2]:
# Scalar (0-D tensor)
a = torch.tensor(5)

# Vector (1-D tensor)
b = torch.tensor([1, 2, 3])

# Matrix (2-D tensor)
c = torch.tensor([[1, 2],
                  [3, 4]])

print(a)
print(b)
print(c)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [3]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)

print("Tensor:", x)
print("Data type:", x.dtype)
print("Shape:", x.shape)

Tensor: tensor([1., 2., 3.])
Data type: torch.float32
Shape: torch.Size([3])


In [4]:
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)
random = torch.rand(2, 3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random:\n", random)

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random:
 tensor([[0.6302, 0.9962, 0.1387],
        [0.7413, 0.6639, 0.9882]])


In [5]:
A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([10, 20])

print(A + B)

tensor([[11, 22],
        [13, 24]])


In [6]:
M = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("First row:", M[0])
print("Second column:", M[:, 1])

# Reshape
reshaped = M.reshape(3, 2)
print("Reshaped:\n", reshaped)

First row: tensor([1, 2, 3])
Second column: tensor([2, 5])
Reshaped:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [7]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2*x + 1

y.backward()

print("Gradient dy/dx:", x.grad)

Gradient dy/dx: tensor(8.)


In [9]:
import tensorflow as tf

In [10]:
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

# Matrix addition
print("Addition:\n", A + B)

# Matrix multiplication
print("Multiplication:\n", tf.matmul(A, B))

# Transpose
print("Transpose:\n", tf.transpose(A))

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [11]:
def step(x):
    return 1 if x >= 0 else 0

def AND(x1, x2):
    w1, w2, b = 1, 1, -1.5
    return step(w1*x1 + w2*x2 + b)

for x1 in [0,1]:
    for x2 in [0,1]:
        print(x1, x2, AND(x1, x2))

0 0 0
0 1 0
1 0 0
1 1 1


In [12]:
def OR(x1, x2):
    w1, w2, b = 1, 1, -0.5
    return step(w1*x1 + w2*x2 + b)

for x1 in [0,1]:
    for x2 in [0,1]:
        print(x1, x2, OR(x1, x2))

0 0 0
0 1 1
1 0 1
1 1 1


In [13]:
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])

y = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])

In [14]:
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2),
    torch.nn.ReLU(),
    torch.nn.Linear(2, 1),
    torch.nn.Sigmoid()
)

loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [15]:
for epoch in range(5000):
    y_pred = model(X)
    loss = loss_fn(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("Final Output:\n", model(X))

Final Output:
 tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [16]:
X = torch.unsqueeze(torch.linspace(0, 10, 100), dim=1)
y = 3*X + 2

In [17]:
model = torch.nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(1000):
    y_pred = model(X)
    loss = loss_fn(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("Predicted for x=5:", model(torch.tensor([[5.]])))

Predicted for x=5: tensor([[16.9966]], grad_fn=<AddmmBackward0>)
